
package com.soaplite.namespaces.perl;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
import uri.ecare.ObjectFactory;
import uri.ecare.PaymentechCcDl;
import uri.ecare.UkashVoucherDl;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "ECarePortType", targetNamespace = "http://namespaces.soaplite.com/perl")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ECarePortType {


    /**
     * 
     * @param phoneNo
     * @param paymentechCcDl
     * @param businessUnit
     * @param userId
     * @param clientId
     * @return
     *     returns uri.ecare.PrepaidPaymentechPaymentDlResponse.ECarePrepaidPaymentechResponse
     */
    @WebMethod(operationName = "prepaid_paymentech_payment_dl", action = "urn:ECare::Prepaid")
    @WebResult(name = "ECare__PrepaidPaymentechResponse", targetNamespace = "")
    @RequestWrapper(localName = "prepaid_paymentech_payment_dl", targetNamespace = "uri:ECare", className = "uri.ecare.PrepaidPaymentechPaymentDl")
    @ResponseWrapper(localName = "prepaid_paymentech_payment_dlResponse", targetNamespace = "uri:ECare", className = "uri.ecare.PrepaidPaymentechPaymentDlResponse")
    public uri.ecare.PrepaidPaymentechPaymentDlResponse.ECarePrepaidPaymentechResponse prepaidPaymentechPaymentDl(
        @WebParam(name = "user_id", targetNamespace = "")
        String userId,
        @WebParam(name = "business_unit", targetNamespace = "")
        String businessUnit,
        @WebParam(name = "client_id", targetNamespace = "")
        String clientId,
        @WebParam(name = "phone_no", targetNamespace = "")
        String phoneNo,
        @WebParam(name = "paymentech_cc_dl", targetNamespace = "uri:ECare")
        PaymentechCcDl paymentechCcDl);

    /**
     * 
     * @param phoneNo
     * @param businessUnit
     * @param ukashVoucherDl
     * @param userId
     * @param clientId
     * @return
     *     returns uri.ecare.PrepaidUkashPaymentDlResponse.ECarePrepaidUkashResponse
     */
    @WebMethod(operationName = "prepaid_ukash_payment_dl", action = "urn:ECare::Prepaid")
    @WebResult(name = "ECare__PrepaidUkashResponse", targetNamespace = "")
    @RequestWrapper(localName = "prepaid_ukash_payment_dl", targetNamespace = "uri:ECare", className = "uri.ecare.PrepaidUkashPaymentDl")
    @ResponseWrapper(localName = "prepaid_ukash_payment_dlResponse", targetNamespace = "uri:ECare", className = "uri.ecare.PrepaidUkashPaymentDlResponse")
    public uri.ecare.PrepaidUkashPaymentDlResponse.ECarePrepaidUkashResponse prepaidUkashPaymentDl(
        @WebParam(name = "user_id", targetNamespace = "")
        String userId,
        @WebParam(name = "business_unit", targetNamespace = "")
        String businessUnit,
        @WebParam(name = "client_id", targetNamespace = "")
        String clientId,
        @WebParam(name = "phone_no", targetNamespace = "")
        String phoneNo,
        @WebParam(name = "ukash_voucher_dl", targetNamespace = "uri:ECare")
        UkashVoucherDl ukashVoucherDl);

    /**
     * 
     * @param phoneNo
     * @return
     *     returns uri.ecare.GetPrepaidBalanceDlResponse.ECarePrepaidBalanceResponse
     */
    @WebMethod(operationName = "get_prepaid_balance_dl", action = "urn:ECare::Prepaid")
    @WebResult(name = "ECare__PrepaidBalanceResponse", targetNamespace = "")
    @RequestWrapper(localName = "get_prepaid_balance_dl", targetNamespace = "uri:ECare", className = "uri.ecare.GetPrepaidBalanceDl")
    @ResponseWrapper(localName = "get_prepaid_balance_dlResponse", targetNamespace = "uri:ECare", className = "uri.ecare.GetPrepaidBalanceDlResponse")
    public uri.ecare.GetPrepaidBalanceDlResponse.ECarePrepaidBalanceResponse getPrepaidBalanceDl(
        @WebParam(name = "phone_no", targetNamespace = "")
        String phoneNo);

}
