
package com.soaplite.namespaces.perl;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.jws.HandlerChain;

/**
 * gSOAP 2.3.8 generated service definition
 * 
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "ECare", targetNamespace = "http://namespaces.soaplite.com/perl", wsdlLocation = "PrimusWS.wsdl")
@HandlerChain(file="handler-chain.xml")
public class ECare
    extends Service
{

    private final static URL ECARE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(com.soaplite.namespaces.perl.ECare.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = com.soaplite.namespaces.perl.ECare.class.getResource(".");
            url = new URL(baseUrl, "PrimusWS.wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'PrimusWS.wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        ECARE_WSDL_LOCATION = url;
    }

    public ECare(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ECare() {
        super(ECARE_WSDL_LOCATION, new QName("http://namespaces.soaplite.com/perl", "ECare"));
    }

    /**
     * 
     * @return
     *     returns ECarePortType
     */
    @WebEndpoint(name = "ECare")
    public ECarePortType getECare() {
        return super.getPort(new QName("http://namespaces.soaplite.com/perl", "ECare"), ECarePortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ECarePortType
     */
    @WebEndpoint(name = "ECare")
    public ECarePortType getECare(WebServiceFeature... features) {
        return super.getPort(new QName("http://namespaces.soaplite.com/perl", "ECare"), ECarePortType.class, features);
    }

}
