//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0-b52-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.08.13 at 03:24:53 PM EDT 
//


package com.primus.pl.xml;

import java.math.BigDecimal;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ActivationRequest complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ActivationRequest">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;all>
 *         &lt;element name="lotId" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *         &lt;element name="subscriberPhone" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="initialBalance" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *       &lt;/all>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ActivationRequest", propOrder = {

})
public class ActivationRequest {

    @XmlElement(namespace = "http://primus.com/prepaidLocal/schemas")
    protected long lotId;
    @XmlElement(namespace = "http://primus.com/prepaidLocal/schemas", required = true)
    protected String subscriberPhone;
    @XmlElement(namespace = "http://primus.com/prepaidLocal/schemas", required = true)
    protected BigDecimal initialBalance;

    /**
     * Gets the value of the lotId property.
     * 
     */
    public long getLotId() {
        return lotId;
    }

    /**
     * Sets the value of the lotId property.
     * 
     */
    public void setLotId(long value) {
        this.lotId = value;
    }

    /**
     * Gets the value of the subscriberPhone property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSubscriberPhone() {
        return subscriberPhone;
    }

    /**
     * Sets the value of the subscriberPhone property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSubscriberPhone(String value) {
        this.subscriberPhone = value;
    }

    /**
     * Gets the value of the initialBalance property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getInitialBalance() {
        return initialBalance;
    }

    /**
     * Sets the value of the initialBalance property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setInitialBalance(BigDecimal value) {
        this.initialBalance = value;
    }

}
