//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0-b52-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.05.06 at 02:12:11 AM EDT 
//


package com.primus.pl.xml;

import java.math.BigInteger;


public class ActivationResponse {

    protected Integer code;
    protected String message;
    protected Long subscriberId;
    protected String subscriberPin;
    
    public ActivationResponse() {}

	public Integer getCode() {
		return code;
	}

	public void setCode(Integer code) {
		this.code = code;
	}

	public String getMessage() {
		return message;
	}

	public void setMessage(String message) {
		this.message = message;
	}

	public String getSubscriberPin() {
		return subscriberPin;
	}

	public void setSubscriberPin(String subscriberPin) {
		this.subscriberPin = subscriberPin;
	}

	public Long getSubscriberId() {
		return subscriberId;
	}

	public void setSubscriberId(Long subscriberId) {
		this.subscriberId = subscriberId;
	}

 }
