//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0-b52-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.08.12 at 04:26:29 PM EDT 
//


package com.primus.pl.xml;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for CreditCardProcessorResponse complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CreditCardProcessorResponse">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;all>
 *         &lt;element name="authorizationCode" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="resultCode" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="resultDescription" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="avsResultCode" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="avsResultDescription" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="inquiryId" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/all>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CreditCardProcessorResponse", propOrder = {

})
public class CreditCardProcessorResponse {

    @XmlElement(namespace = "http://primus.com/prepaidLocal/schemas", required = true)
    protected String authorizationCode;
    @XmlElement(namespace = "http://primus.com/prepaidLocal/schemas", required = true)
    protected String resultCode;
    @XmlElement(namespace = "http://primus.com/prepaidLocal/schemas", required = true)
    protected String resultDescription;
    @XmlElement(namespace = "http://primus.com/prepaidLocal/schemas", required = true)
    protected String avsResultCode;
    @XmlElement(namespace = "http://primus.com/prepaidLocal/schemas", required = true)
    protected String avsResultDescription;
    @XmlElement(namespace = "http://primus.com/prepaidLocal/schemas", required = true)
    protected String inquiryId;

    /**
     * Gets the value of the authorizationCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAuthorizationCode() {
        return authorizationCode;
    }

    /**
     * Sets the value of the authorizationCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAuthorizationCode(String value) {
        this.authorizationCode = value;
    }

    /**
     * Gets the value of the resultCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getResultCode() {
        return resultCode;
    }

    /**
     * Sets the value of the resultCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setResultCode(String value) {
        this.resultCode = value;
    }

    /**
     * Gets the value of the resultDescription property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getResultDescription() {
        return resultDescription;
    }

    /**
     * Sets the value of the resultDescription property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setResultDescription(String value) {
        this.resultDescription = value;
    }

    /**
     * Gets the value of the avsResultCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAvsResultCode() {
        return avsResultCode;
    }

    /**
     * Sets the value of the avsResultCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAvsResultCode(String value) {
        this.avsResultCode = value;
    }

    /**
     * Gets the value of the avsResultDescription property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAvsResultDescription() {
        return avsResultDescription;
    }

    /**
     * Sets the value of the avsResultDescription property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAvsResultDescription(String value) {
        this.avsResultDescription = value;
    }

    /**
     * Gets the value of the inquiryId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInquiryId() {
        return inquiryId;
    }

    /**
     * Sets the value of the inquiryId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInquiryId(String value) {
        this.inquiryId = value;
    }

}
