//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0-b52-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.08.14 at 09:18:31 AM EDT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://primus.com/prepaidLocal/schemas")
package com.primus.pl.xml;
