# /etc/bashrc
export LANG=en_US.UTF-8
export LANGVAR=en_US.UTF-8
export LANGUAGE=en
export PCS_USER=pcs
export PS_ROOT=/opt/pcs
export PATH=$PATH:$PS_ROOT/bin:$PS_ROOT/scripts
export LD_LIBRARY_PATH=$PS_ROOT/bin:/opt/java/jre/lib/i386/native_threads/:/opt/java/jre/lib/i386/server
# Source global definitions
if [ -f /etc/bashrc ]; then
    . /etc/bashrc
fi

# Uncomment and modify the lines below to set up your Java environment.
export JAVA_HOME=/opt/java
#export LD_LIBRARY_PATH=$PS_ROOT/bin:$JAVA_HOME/lib/i386/server/:$JAVA_HOME/lib/i386/native_threads:$JAVA_HOME/lib/i386:$LD_LIBRARY_PATH
export JAVA_LIB_PATH=$JAVA_HOME/lib/i386/native_threads:$JAVA_HOME/lib/i386/server:$JAVA_HOME/lib/i386
export PATH=$JAVA_HOME/bin:$PATH

export CLASSPATH=$PS_ROOT/java:$CLASSPATH

export JAR_LOCATION=/opt/pcs/java

export CLASSPATH=$JAR_LOCATION
export CLASSPATH=$JAR_LOCATION/spring-beans.dtd:$CLASSPATH
export CLASSPATH=$JAR_LOCATION/spring.jar:$CLASSPATH
export CLASSPATH=$JAR_LOCATION/pcs_framework.jar:$CLASSPATH
export CLASSPATH=$JAR_LOCATION/pcs_commons.jar:$CLASSPATH
export CLASSPATH=$JAR_LOCATION/commons-beanutils.jar:$CLASSPATH
export CLASSPATH=$JAR_LOCATION/commons-collections.jar:$CLASSPATH
export CLASSPATH=$JAR_LOCATION/commons-dbcp.jar:$CLASSPATH
export CLASSPATH=$JAR_LOCATION/commons-pool.jar:$CLASSPATH
export CLASSPATH=$JAR_LOCATION/commons-logging-1.1.jar:$CLASSPATH
export CLASSPATH=$JAR_LOCATION/log4j-1.2.13.jar:$CLASSPATH
#export CLASSPATH=$JAR_LOCATION/mysql-connector-java-5.0.3-bin.jar:$CLASSPATH
export CLASSPATH=$JAR_LOCATION/mysql-connector-java-5.0.7-bin.jar:$CLASSPATH
export CLASSPATH=$JAR_LOCATION/spring-beans.jar:$CLASSPATH
export CLASSPATH=$JAR_LOCATION/beans.xml:$CLASSPATH
export CLASSPATH=$JAR_LOCATION/log4j.properties:$CLASSPATH
export CLASSPATH=$JAR_LOCATION/delegate.jar:$CLASSPATH
export CLASSPATH=$JAR_LOCATION/TMG.jar:$CLASSPATH
export CLASSPATH=$JAR_LOCATION/IVR555.jar:$CLASSPATH
export CLASSPATH=$JAR_LOCATION/pcs_mutables.jar:$CLASSPATH
export CLASSPATH=$JAR_LOCATION/soapclient_admin.jar:$CLASSPATH
export CLASSPATH=$JAR_LOCATION/soapclient_portal.jar:$CLASSPATH
export CLASSPATH=$JAR_LOCATION/jaxrpc-spi.jar:$CLASSPATH
export CLASSPATH=$JAR_LOCATION/jaxrpc-api.jar:$CLASSPATH
export CLASSPATH=$JAR_LOCATION/jaxrpc-impl.jar:$CLASSPATH
export CLASSPATH=$JAR_LOCATION/activation.jar:$CLASSPATH
export CLASSPATH=$JAR_LOCATION/mail.jar:$CLASSPATH
export CLASSPATH=$JAR_LOCATION/saaj-api.jar:$CLASSPATH
export CLASSPATH=$JAR_LOCATION/saaj-impl.jar:$CLASSPATH
export CLASSPATH=$JAR_LOCATION/FastInfoset.jar:$CLASSPATH
export CLASSPATH=$JAR_LOCATION/jaxp-api.jar:$CLASSPATH
export CLASSPATH=$JAR_LOCATION/jsr173_api.jar:$CLASSPATH
export CLASSPATH=$JAR_LOCATION/commons-io-1.1.jar:$CLASSPATH
export CLASSPATH=$JAR_LOCATION/sjsxp.jar:$CLASSPATH
export CLASSPATH=$JAR_LOCATION/ojdbc14.jar:$CLASSPATH

# Uncomment the line below if you need core files
#ulimit -S -c unlimited > /dev/null 2>&1
# vim:ts=4:sw=4
