--in pcssystem
CREATE SEQUENCE SUSPEND_TRACKING_SEQ MINVALUE 1 START WITH 10000 MAXVALUE 9999999999 INCREMENT BY 3 CACHE 20 NOORDER CYCLE ;

GRANT SELECT ON SUSPEND_TRACKING_SEQ TO PUBLIC ;


--in pcsprod

CREATE SYNONYM SUSPEND_TRACKING_SEQ FOR pcssystem.SUSPEND_TRACKING_SEQ ;

CREATE TABLE SUSPEND_TRACKING(
	ID NUMBER PRIMARY KEY,
	SUBSCRIBER_ID NUMBER NOT NULL,
	PHONE_NUMBER VARCHAR(20) NOT NULL,
	AA_ACTIVITY_ID VARCHAR(20) NOT NULL,
	SUSPENDED_ON DATE NOT NULL,
	UNSUSPENDED_ON DATE
) ;
  
