package com.beachdog.primusCore.model;

// Generated Mar 1, 2012 2:19:03 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;

/**
 * AuditEvent generated by hbm2java
 */
public class AuditEvent implements java.io.Serializable {

	private BigDecimal auditEventId;
	private String name;
	private String dataCol1Desc;
	private String dataCol2Desc;
	private String dataCol3Desc;
	private String dataCol4Desc;
	private String dataCol5Desc;

	public AuditEvent() {
	}

	public AuditEvent(BigDecimal auditEventId) {
		this.auditEventId = auditEventId;
	}

	public AuditEvent(BigDecimal auditEventId, String name,
			String dataCol1Desc, String dataCol2Desc, String dataCol3Desc,
			String dataCol4Desc, String dataCol5Desc) {
		this.auditEventId = auditEventId;
		this.name = name;
		this.dataCol1Desc = dataCol1Desc;
		this.dataCol2Desc = dataCol2Desc;
		this.dataCol3Desc = dataCol3Desc;
		this.dataCol4Desc = dataCol4Desc;
		this.dataCol5Desc = dataCol5Desc;
	}

	public BigDecimal getAuditEventId() {
		return this.auditEventId;
	}

	public void setAuditEventId(BigDecimal auditEventId) {
		this.auditEventId = auditEventId;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getDataCol1Desc() {
		return this.dataCol1Desc;
	}

	public void setDataCol1Desc(String dataCol1Desc) {
		this.dataCol1Desc = dataCol1Desc;
	}

	public String getDataCol2Desc() {
		return this.dataCol2Desc;
	}

	public void setDataCol2Desc(String dataCol2Desc) {
		this.dataCol2Desc = dataCol2Desc;
	}

	public String getDataCol3Desc() {
		return this.dataCol3Desc;
	}

	public void setDataCol3Desc(String dataCol3Desc) {
		this.dataCol3Desc = dataCol3Desc;
	}

	public String getDataCol4Desc() {
		return this.dataCol4Desc;
	}

	public void setDataCol4Desc(String dataCol4Desc) {
		this.dataCol4Desc = dataCol4Desc;
	}

	public String getDataCol5Desc() {
		return this.dataCol5Desc;
	}

	public void setDataCol5Desc(String dataCol5Desc) {
		this.dataCol5Desc = dataCol5Desc;
	}

}
