package com.beachdog.primusCore.model;

// Generated Mar 1, 2012 2:19:03 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;

/**
 * EvtPointOfSale generated by hbm2java
 */
public class EvtPointOfSale implements java.io.Serializable {

	private BigDecimal posEventId;
	private CurrencyRef currencyRef;
	private ProductOffering productOffering;
	private String serialNumber;
	private String custTransactionCode;
	private String pcsTransactionCode;
	private String interfaceCode;
	private Date timeStamp;
	private String responseCode;
	private String custData1;
	private String custData2;
	private BigDecimal subscriberId;
	private BigDecimal amount;
	private String activityId;
	private String userName;

	public EvtPointOfSale() {
	}

	public EvtPointOfSale(BigDecimal posEventId, String serialNumber,
			String custTransactionCode, String pcsTransactionCode,
			String interfaceCode, Date timeStamp, String responseCode) {
		this.posEventId = posEventId;
		this.serialNumber = serialNumber;
		this.custTransactionCode = custTransactionCode;
		this.pcsTransactionCode = pcsTransactionCode;
		this.interfaceCode = interfaceCode;
		this.timeStamp = timeStamp;
		this.responseCode = responseCode;
	}

	public EvtPointOfSale(BigDecimal posEventId, CurrencyRef currencyRef,
			ProductOffering productOffering, String serialNumber,
			String custTransactionCode, String pcsTransactionCode,
			String interfaceCode, Date timeStamp, String responseCode,
			String custData1, String custData2, BigDecimal subscriberId,
			BigDecimal amount, String activityId, String userName) {
		this.posEventId = posEventId;
		this.currencyRef = currencyRef;
		this.productOffering = productOffering;
		this.serialNumber = serialNumber;
		this.custTransactionCode = custTransactionCode;
		this.pcsTransactionCode = pcsTransactionCode;
		this.interfaceCode = interfaceCode;
		this.timeStamp = timeStamp;
		this.responseCode = responseCode;
		this.custData1 = custData1;
		this.custData2 = custData2;
		this.subscriberId = subscriberId;
		this.amount = amount;
		this.activityId = activityId;
		this.userName = userName;
	}

	public BigDecimal getPosEventId() {
		return this.posEventId;
	}

	public void setPosEventId(BigDecimal posEventId) {
		this.posEventId = posEventId;
	}

	public CurrencyRef getCurrencyRef() {
		return this.currencyRef;
	}

	public void setCurrencyRef(CurrencyRef currencyRef) {
		this.currencyRef = currencyRef;
	}

	public ProductOffering getProductOffering() {
		return this.productOffering;
	}

	public void setProductOffering(ProductOffering productOffering) {
		this.productOffering = productOffering;
	}

	public String getSerialNumber() {
		return this.serialNumber;
	}

	public void setSerialNumber(String serialNumber) {
		this.serialNumber = serialNumber;
	}

	public String getCustTransactionCode() {
		return this.custTransactionCode;
	}

	public void setCustTransactionCode(String custTransactionCode) {
		this.custTransactionCode = custTransactionCode;
	}

	public String getPcsTransactionCode() {
		return this.pcsTransactionCode;
	}

	public void setPcsTransactionCode(String pcsTransactionCode) {
		this.pcsTransactionCode = pcsTransactionCode;
	}

	public String getInterfaceCode() {
		return this.interfaceCode;
	}

	public void setInterfaceCode(String interfaceCode) {
		this.interfaceCode = interfaceCode;
	}

	public Date getTimeStamp() {
		return this.timeStamp;
	}

	public void setTimeStamp(Date timeStamp) {
		this.timeStamp = timeStamp;
	}

	public String getResponseCode() {
		return this.responseCode;
	}

	public void setResponseCode(String responseCode) {
		this.responseCode = responseCode;
	}

	public String getCustData1() {
		return this.custData1;
	}

	public void setCustData1(String custData1) {
		this.custData1 = custData1;
	}

	public String getCustData2() {
		return this.custData2;
	}

	public void setCustData2(String custData2) {
		this.custData2 = custData2;
	}

	public BigDecimal getSubscriberId() {
		return this.subscriberId;
	}

	public void setSubscriberId(BigDecimal subscriberId) {
		this.subscriberId = subscriberId;
	}

	public BigDecimal getAmount() {
		return this.amount;
	}

	public void setAmount(BigDecimal amount) {
		this.amount = amount;
	}

	public String getActivityId() {
		return this.activityId;
	}

	public void setActivityId(String activityId) {
		this.activityId = activityId;
	}

	public String getUserName() {
		return this.userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

}
