package com.beachdog.primusCore.model;

// Generated Mar 1, 2012 2:19:03 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;

/**
 * EvtPrepaidActivationLogId generated by hbm2java
 */
public class EvtPrepaidActivationLogId implements java.io.Serializable {

	private BigDecimal auditId;
	private String activationId;

	public EvtPrepaidActivationLogId() {
	}

	public EvtPrepaidActivationLogId(BigDecimal auditId, String activationId) {
		this.auditId = auditId;
		this.activationId = activationId;
	}

	public BigDecimal getAuditId() {
		return this.auditId;
	}

	public void setAuditId(BigDecimal auditId) {
		this.auditId = auditId;
	}

	public String getActivationId() {
		return this.activationId;
	}

	public void setActivationId(String activationId) {
		this.activationId = activationId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof EvtPrepaidActivationLogId))
			return false;
		EvtPrepaidActivationLogId castOther = (EvtPrepaidActivationLogId) other;

		return ((this.getAuditId() == castOther.getAuditId()) || (this
				.getAuditId() != null && castOther.getAuditId() != null && this
				.getAuditId().equals(castOther.getAuditId())))
				&& ((this.getActivationId() == castOther.getActivationId()) || (this
						.getActivationId() != null
						&& castOther.getActivationId() != null && this
						.getActivationId().equals(castOther.getActivationId())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getAuditId() == null ? 0 : this.getAuditId().hashCode());
		result = 37
				* result
				+ (getActivationId() == null ? 0 : this.getActivationId()
						.hashCode());
		return result;
	}

}
