package com.beachdog.primusCore.model;

// Generated Mar 1, 2012 2:19:03 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;

/**
 * EvtRechargeTransaction generated by hbm2java
 */
public class EvtRechargeTransaction implements java.io.Serializable {

	private String eventId;
	private CurrencyRef currencyRef;
	private Subscriber subscriber;
	private Date timeStamp;
	private Character transactionType;
	private Character removeFlag;
	private BigDecimal creditCardId;
	private BigDecimal auditId;
	private BigDecimal sessionType;
	private BigDecimal amount;
	private BigDecimal transactionResult;
	private BigDecimal initiatedBy;
	private String cybersourceResultCode;
	private String authorizationNumber;
	private String sessionId;
	private String cybersourceRequestId;
	private String replyMessage;

	public EvtRechargeTransaction() {
	}

	public EvtRechargeTransaction(String eventId, CurrencyRef currencyRef,
			Date timeStamp) {
		this.eventId = eventId;
		this.currencyRef = currencyRef;
		this.timeStamp = timeStamp;
	}

	public EvtRechargeTransaction(String eventId, CurrencyRef currencyRef,
			Subscriber subscriber, Date timeStamp, Character transactionType,
			Character removeFlag, BigDecimal creditCardId, BigDecimal auditId,
			BigDecimal sessionType, BigDecimal amount,
			BigDecimal transactionResult, BigDecimal initiatedBy,
			String cybersourceResultCode, String authorizationNumber,
			String sessionId, String cybersourceRequestId, String replyMessage) {
		this.eventId = eventId;
		this.currencyRef = currencyRef;
		this.subscriber = subscriber;
		this.timeStamp = timeStamp;
		this.transactionType = transactionType;
		this.removeFlag = removeFlag;
		this.creditCardId = creditCardId;
		this.auditId = auditId;
		this.sessionType = sessionType;
		this.amount = amount;
		this.transactionResult = transactionResult;
		this.initiatedBy = initiatedBy;
		this.cybersourceResultCode = cybersourceResultCode;
		this.authorizationNumber = authorizationNumber;
		this.sessionId = sessionId;
		this.cybersourceRequestId = cybersourceRequestId;
		this.replyMessage = replyMessage;
	}

	public String getEventId() {
		return this.eventId;
	}

	public void setEventId(String eventId) {
		this.eventId = eventId;
	}

	public CurrencyRef getCurrencyRef() {
		return this.currencyRef;
	}

	public void setCurrencyRef(CurrencyRef currencyRef) {
		this.currencyRef = currencyRef;
	}

	public Subscriber getSubscriber() {
		return this.subscriber;
	}

	public void setSubscriber(Subscriber subscriber) {
		this.subscriber = subscriber;
	}

	public Date getTimeStamp() {
		return this.timeStamp;
	}

	public void setTimeStamp(Date timeStamp) {
		this.timeStamp = timeStamp;
	}

	public Character getTransactionType() {
		return this.transactionType;
	}

	public void setTransactionType(Character transactionType) {
		this.transactionType = transactionType;
	}

	public Character getRemoveFlag() {
		return this.removeFlag;
	}

	public void setRemoveFlag(Character removeFlag) {
		this.removeFlag = removeFlag;
	}

	public BigDecimal getCreditCardId() {
		return this.creditCardId;
	}

	public void setCreditCardId(BigDecimal creditCardId) {
		this.creditCardId = creditCardId;
	}

	public BigDecimal getAuditId() {
		return this.auditId;
	}

	public void setAuditId(BigDecimal auditId) {
		this.auditId = auditId;
	}

	public BigDecimal getSessionType() {
		return this.sessionType;
	}

	public void setSessionType(BigDecimal sessionType) {
		this.sessionType = sessionType;
	}

	public BigDecimal getAmount() {
		return this.amount;
	}

	public void setAmount(BigDecimal amount) {
		this.amount = amount;
	}

	public BigDecimal getTransactionResult() {
		return this.transactionResult;
	}

	public void setTransactionResult(BigDecimal transactionResult) {
		this.transactionResult = transactionResult;
	}

	public BigDecimal getInitiatedBy() {
		return this.initiatedBy;
	}

	public void setInitiatedBy(BigDecimal initiatedBy) {
		this.initiatedBy = initiatedBy;
	}

	public String getCybersourceResultCode() {
		return this.cybersourceResultCode;
	}

	public void setCybersourceResultCode(String cybersourceResultCode) {
		this.cybersourceResultCode = cybersourceResultCode;
	}

	public String getAuthorizationNumber() {
		return this.authorizationNumber;
	}

	public void setAuthorizationNumber(String authorizationNumber) {
		this.authorizationNumber = authorizationNumber;
	}

	public String getSessionId() {
		return this.sessionId;
	}

	public void setSessionId(String sessionId) {
		this.sessionId = sessionId;
	}

	public String getCybersourceRequestId() {
		return this.cybersourceRequestId;
	}

	public void setCybersourceRequestId(String cybersourceRequestId) {
		this.cybersourceRequestId = cybersourceRequestId;
	}

	public String getReplyMessage() {
		return this.replyMessage;
	}

	public void setReplyMessage(String replyMessage) {
		this.replyMessage = replyMessage;
	}

}
