package com.beachdog.primusCore.model;

// Generated Mar 1, 2012 2:19:03 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * LanguageRef generated by hbm2java
 */
public class LanguageRef implements java.io.Serializable {

	private BigDecimal languageId;
	private String name;
	private String languageCode;
	private Set accessNumbers = new HashSet(0);

	public LanguageRef() {
	}

	public LanguageRef(BigDecimal languageId, String languageCode) {
		this.languageId = languageId;
		this.languageCode = languageCode;
	}

	public LanguageRef(BigDecimal languageId, String name, String languageCode,
			Set accessNumbers) {
		this.languageId = languageId;
		this.name = name;
		this.languageCode = languageCode;
		this.accessNumbers = accessNumbers;
	}

	public BigDecimal getLanguageId() {
		return this.languageId;
	}

	public void setLanguageId(BigDecimal languageId) {
		this.languageId = languageId;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getLanguageCode() {
		return this.languageCode;
	}

	public void setLanguageCode(String languageCode) {
		this.languageCode = languageCode;
	}

	public Set getAccessNumbers() {
		return this.accessNumbers;
	}

	public void setAccessNumbers(Set accessNumbers) {
		this.accessNumbers = accessNumbers;
	}

}
