package com.beachdog.primusCore.model;

// Generated Mar 1, 2012 2:19:03 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;

/**
 * PsAudit generated by hbm2java
 */
public class PsAudit implements java.io.Serializable {

	private BigDecimal auditId;
	private Date timestamp;
	private BigDecimal auditEventId;
	private BigDecimal userId;
	private char acdUserFlag;
	private BigDecimal subscriberId;
	private BigDecimal serviceProviderId;
	private String errorCode;
	private String errorDescription;
	private String dataCol1;
	private String dataCol2;
	private String dataCol3;
	private String dataCol4;
	private String dataCol5;

	public PsAudit() {
	}

	public PsAudit(BigDecimal auditId, BigDecimal auditEventId,
			BigDecimal userId, char acdUserFlag) {
		this.auditId = auditId;
		this.auditEventId = auditEventId;
		this.userId = userId;
		this.acdUserFlag = acdUserFlag;
	}

	public PsAudit(BigDecimal auditId, BigDecimal auditEventId,
			BigDecimal userId, char acdUserFlag, BigDecimal subscriberId,
			BigDecimal serviceProviderId, String errorCode,
			String errorDescription, String dataCol1, String dataCol2,
			String dataCol3, String dataCol4, String dataCol5) {
		this.auditId = auditId;
		this.auditEventId = auditEventId;
		this.userId = userId;
		this.acdUserFlag = acdUserFlag;
		this.subscriberId = subscriberId;
		this.serviceProviderId = serviceProviderId;
		this.errorCode = errorCode;
		this.errorDescription = errorDescription;
		this.dataCol1 = dataCol1;
		this.dataCol2 = dataCol2;
		this.dataCol3 = dataCol3;
		this.dataCol4 = dataCol4;
		this.dataCol5 = dataCol5;
	}

	public BigDecimal getAuditId() {
		return this.auditId;
	}

	public void setAuditId(BigDecimal auditId) {
		this.auditId = auditId;
	}

	public Date getTimestamp() {
		return this.timestamp;
	}

	public void setTimestamp(Date timestamp) {
		this.timestamp = timestamp;
	}

	public BigDecimal getAuditEventId() {
		return this.auditEventId;
	}

	public void setAuditEventId(BigDecimal auditEventId) {
		this.auditEventId = auditEventId;
	}

	public BigDecimal getUserId() {
		return this.userId;
	}

	public void setUserId(BigDecimal userId) {
		this.userId = userId;
	}

	public char getAcdUserFlag() {
		return this.acdUserFlag;
	}

	public void setAcdUserFlag(char acdUserFlag) {
		this.acdUserFlag = acdUserFlag;
	}

	public BigDecimal getSubscriberId() {
		return this.subscriberId;
	}

	public void setSubscriberId(BigDecimal subscriberId) {
		this.subscriberId = subscriberId;
	}

	public BigDecimal getServiceProviderId() {
		return this.serviceProviderId;
	}

	public void setServiceProviderId(BigDecimal serviceProviderId) {
		this.serviceProviderId = serviceProviderId;
	}

	public String getErrorCode() {
		return this.errorCode;
	}

	public void setErrorCode(String errorCode) {
		this.errorCode = errorCode;
	}

	public String getErrorDescription() {
		return this.errorDescription;
	}

	public void setErrorDescription(String errorDescription) {
		this.errorDescription = errorDescription;
	}

	public String getDataCol1() {
		return this.dataCol1;
	}

	public void setDataCol1(String dataCol1) {
		this.dataCol1 = dataCol1;
	}

	public String getDataCol2() {
		return this.dataCol2;
	}

	public void setDataCol2(String dataCol2) {
		this.dataCol2 = dataCol2;
	}

	public String getDataCol3() {
		return this.dataCol3;
	}

	public void setDataCol3(String dataCol3) {
		this.dataCol3 = dataCol3;
	}

	public String getDataCol4() {
		return this.dataCol4;
	}

	public void setDataCol4(String dataCol4) {
		this.dataCol4 = dataCol4;
	}

	public String getDataCol5() {
		return this.dataCol5;
	}

	public void setDataCol5(String dataCol5) {
		this.dataCol5 = dataCol5;
	}

}
