package com.beachdog.primusCore.model;

// Generated Jul 22, 2012 6:38:02 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;

/**
 * RatedEvent generated by hbm2java
 */
public class RatedEvent implements java.io.Serializable {

	private BigDecimal ratedEventId;
	private Rate rate;
	private BigDecimal serviceProviderId;
	private BigDecimal eventTypeId;
	private BigDecimal serviceId;
	private BigDecimal productOfferingId;
	private BigDecimal accessNumberId;
	private BigDecimal ratePlanId;

	public RatedEvent() {
	}

	public RatedEvent(BigDecimal ratedEventId, Rate rate,
			BigDecimal serviceProviderId) {
		this.ratedEventId = ratedEventId;
		this.rate = rate;
		this.serviceProviderId = serviceProviderId;
	}

	public RatedEvent(BigDecimal ratedEventId, Rate rate,
			BigDecimal serviceProviderId, BigDecimal eventTypeId,
			BigDecimal serviceId, BigDecimal productOfferingId,
			BigDecimal accessNumberId, BigDecimal ratePlanId) {
		this.ratedEventId = ratedEventId;
		this.rate = rate;
		this.serviceProviderId = serviceProviderId;
		this.eventTypeId = eventTypeId;
		this.serviceId = serviceId;
		this.productOfferingId = productOfferingId;
		this.accessNumberId = accessNumberId;
		this.ratePlanId = ratePlanId;
	}

	public BigDecimal getRatedEventId() {
		return this.ratedEventId;
	}

	public void setRatedEventId(BigDecimal ratedEventId) {
		this.ratedEventId = ratedEventId;
	}

	public Rate getRate() {
		return this.rate;
	}

	public void setRate(Rate rate) {
		this.rate = rate;
	}

	public BigDecimal getServiceProviderId() {
		return this.serviceProviderId;
	}

	public void setServiceProviderId(BigDecimal serviceProviderId) {
		this.serviceProviderId = serviceProviderId;
	}

	public BigDecimal getEventTypeId() {
		return this.eventTypeId;
	}

	public void setEventTypeId(BigDecimal eventTypeId) {
		this.eventTypeId = eventTypeId;
	}

	public BigDecimal getServiceId() {
		return this.serviceId;
	}

	public void setServiceId(BigDecimal serviceId) {
		this.serviceId = serviceId;
	}

	public BigDecimal getProductOfferingId() {
		return this.productOfferingId;
	}

	public void setProductOfferingId(BigDecimal productOfferingId) {
		this.productOfferingId = productOfferingId;
	}

	public BigDecimal getAccessNumberId() {
		return this.accessNumberId;
	}

	public void setAccessNumberId(BigDecimal accessNumberId) {
		this.accessNumberId = accessNumberId;
	}

	public BigDecimal getRatePlanId() {
		return this.ratePlanId;
	}

	public void setRatePlanId(BigDecimal ratePlanId) {
		this.ratePlanId = ratePlanId;
	}

}
