package com.beachdog.primusCore.model;

// Generated Jul 22, 2012 6:38:02 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Rate generated by hbm2java
 */
public class Rate implements java.io.Serializable {

	private BigDecimal rateId;
	private BigDecimal rateTypeId;
	private BigDecimal calcTypeId;
	private BigDecimal defaultAmount;
	private BigDecimal serviceProviderId;
	private BigDecimal eventTypeId;
	private char postEventBillFlag;
	private char bongChargeType;
	private char includeTimeAnnounced;
	private char includeTimeAllowed;
	private char useAccessNumberGroups;
	private BigDecimal maintFeeFrequency;
	private BigDecimal surcharge;
	private BigDecimal subrateNotfoundOption;
	private Date effectiveDate;
	private Date endDate;
	private String description;
	private String rateName;
	private BigDecimal firstMaintFeeFrequency;
	private BigDecimal firstMaintFeeRate;
	private char tdwDiscountFlag;
	private char bucketExhaustionCutoffFlag;
	private char sendViolationNotifications;
	private char sendBucketRefillNotifFlag;
	private char sendBucketExhaustNotifFlag;
	private BigDecimal bucketSize;
	private BigDecimal numBucketRefillsPerCycle;
	private BigDecimal dailyUsageThreshold;
	private BigDecimal bucketRefillWarnThrshld;
	private BigDecimal bucketExhaustWarnThrshld;
	private BigDecimal regionFeeSchedId;
	private char bucketPlanType;
	private char bucketRateCallsFlag;
	private BigDecimal subscriptionFeeFrequency;
	private BigDecimal gracePeriod;
	private BigDecimal amountSetting;
	private BigDecimal surchargeSetting;
	private BigDecimal maintFeeStartSeq;
	private BigDecimal firstUseThreshold;
	private BigDecimal maintFeeDayOfWeek;
	private Set ratedEvents = new HashSet(0);

	public Rate() {
	}

	public Rate(BigDecimal rateId, BigDecimal rateTypeId,
			BigDecimal calcTypeId, BigDecimal defaultAmount,
			BigDecimal serviceProviderId, BigDecimal eventTypeId,
			char postEventBillFlag, char bongChargeType,
			char includeTimeAnnounced, char includeTimeAllowed,
			char useAccessNumberGroups, char tdwDiscountFlag,
			char bucketExhaustionCutoffFlag, char sendViolationNotifications,
			char sendBucketRefillNotifFlag, char sendBucketExhaustNotifFlag,
			char bucketPlanType, char bucketRateCallsFlag,
			BigDecimal gracePeriod) {
		this.rateId = rateId;
		this.rateTypeId = rateTypeId;
		this.calcTypeId = calcTypeId;
		this.defaultAmount = defaultAmount;
		this.serviceProviderId = serviceProviderId;
		this.eventTypeId = eventTypeId;
		this.postEventBillFlag = postEventBillFlag;
		this.bongChargeType = bongChargeType;
		this.includeTimeAnnounced = includeTimeAnnounced;
		this.includeTimeAllowed = includeTimeAllowed;
		this.useAccessNumberGroups = useAccessNumberGroups;
		this.tdwDiscountFlag = tdwDiscountFlag;
		this.bucketExhaustionCutoffFlag = bucketExhaustionCutoffFlag;
		this.sendViolationNotifications = sendViolationNotifications;
		this.sendBucketRefillNotifFlag = sendBucketRefillNotifFlag;
		this.sendBucketExhaustNotifFlag = sendBucketExhaustNotifFlag;
		this.bucketPlanType = bucketPlanType;
		this.bucketRateCallsFlag = bucketRateCallsFlag;
		this.gracePeriod = gracePeriod;
	}

	public Rate(BigDecimal rateId, BigDecimal rateTypeId,
			BigDecimal calcTypeId, BigDecimal defaultAmount,
			BigDecimal serviceProviderId, BigDecimal eventTypeId,
			char postEventBillFlag, char bongChargeType,
			char includeTimeAnnounced, char includeTimeAllowed,
			char useAccessNumberGroups, BigDecimal maintFeeFrequency,
			BigDecimal surcharge, BigDecimal subrateNotfoundOption,
			Date effectiveDate, Date endDate, String description,
			String rateName, BigDecimal firstMaintFeeFrequency,
			BigDecimal firstMaintFeeRate, char tdwDiscountFlag,
			char bucketExhaustionCutoffFlag, char sendViolationNotifications,
			char sendBucketRefillNotifFlag, char sendBucketExhaustNotifFlag,
			BigDecimal bucketSize, BigDecimal numBucketRefillsPerCycle,
			BigDecimal dailyUsageThreshold, BigDecimal bucketRefillWarnThrshld,
			BigDecimal bucketExhaustWarnThrshld, BigDecimal regionFeeSchedId,
			char bucketPlanType, char bucketRateCallsFlag,
			BigDecimal subscriptionFeeFrequency, BigDecimal gracePeriod,
			BigDecimal amountSetting, BigDecimal surchargeSetting,
			BigDecimal maintFeeStartSeq, BigDecimal firstUseThreshold,
			BigDecimal maintFeeDayOfWeek, Set ratedEvents) {
		this.rateId = rateId;
		this.rateTypeId = rateTypeId;
		this.calcTypeId = calcTypeId;
		this.defaultAmount = defaultAmount;
		this.serviceProviderId = serviceProviderId;
		this.eventTypeId = eventTypeId;
		this.postEventBillFlag = postEventBillFlag;
		this.bongChargeType = bongChargeType;
		this.includeTimeAnnounced = includeTimeAnnounced;
		this.includeTimeAllowed = includeTimeAllowed;
		this.useAccessNumberGroups = useAccessNumberGroups;
		this.maintFeeFrequency = maintFeeFrequency;
		this.surcharge = surcharge;
		this.subrateNotfoundOption = subrateNotfoundOption;
		this.effectiveDate = effectiveDate;
		this.endDate = endDate;
		this.description = description;
		this.rateName = rateName;
		this.firstMaintFeeFrequency = firstMaintFeeFrequency;
		this.firstMaintFeeRate = firstMaintFeeRate;
		this.tdwDiscountFlag = tdwDiscountFlag;
		this.bucketExhaustionCutoffFlag = bucketExhaustionCutoffFlag;
		this.sendViolationNotifications = sendViolationNotifications;
		this.sendBucketRefillNotifFlag = sendBucketRefillNotifFlag;
		this.sendBucketExhaustNotifFlag = sendBucketExhaustNotifFlag;
		this.bucketSize = bucketSize;
		this.numBucketRefillsPerCycle = numBucketRefillsPerCycle;
		this.dailyUsageThreshold = dailyUsageThreshold;
		this.bucketRefillWarnThrshld = bucketRefillWarnThrshld;
		this.bucketExhaustWarnThrshld = bucketExhaustWarnThrshld;
		this.regionFeeSchedId = regionFeeSchedId;
		this.bucketPlanType = bucketPlanType;
		this.bucketRateCallsFlag = bucketRateCallsFlag;
		this.subscriptionFeeFrequency = subscriptionFeeFrequency;
		this.gracePeriod = gracePeriod;
		this.amountSetting = amountSetting;
		this.surchargeSetting = surchargeSetting;
		this.maintFeeStartSeq = maintFeeStartSeq;
		this.firstUseThreshold = firstUseThreshold;
		this.maintFeeDayOfWeek = maintFeeDayOfWeek;
		this.ratedEvents = ratedEvents;
	}

	public BigDecimal getRateId() {
		return this.rateId;
	}

	public void setRateId(BigDecimal rateId) {
		this.rateId = rateId;
	}

	public BigDecimal getRateTypeId() {
		return this.rateTypeId;
	}

	public void setRateTypeId(BigDecimal rateTypeId) {
		this.rateTypeId = rateTypeId;
	}

	public BigDecimal getCalcTypeId() {
		return this.calcTypeId;
	}

	public void setCalcTypeId(BigDecimal calcTypeId) {
		this.calcTypeId = calcTypeId;
	}

	public BigDecimal getDefaultAmount() {
		return this.defaultAmount;
	}

	public void setDefaultAmount(BigDecimal defaultAmount) {
		this.defaultAmount = defaultAmount;
	}

	public BigDecimal getServiceProviderId() {
		return this.serviceProviderId;
	}

	public void setServiceProviderId(BigDecimal serviceProviderId) {
		this.serviceProviderId = serviceProviderId;
	}

	public BigDecimal getEventTypeId() {
		return this.eventTypeId;
	}

	public void setEventTypeId(BigDecimal eventTypeId) {
		this.eventTypeId = eventTypeId;
	}

	public char getPostEventBillFlag() {
		return this.postEventBillFlag;
	}

	public void setPostEventBillFlag(char postEventBillFlag) {
		this.postEventBillFlag = postEventBillFlag;
	}

	public char getBongChargeType() {
		return this.bongChargeType;
	}

	public void setBongChargeType(char bongChargeType) {
		this.bongChargeType = bongChargeType;
	}

	public char getIncludeTimeAnnounced() {
		return this.includeTimeAnnounced;
	}

	public void setIncludeTimeAnnounced(char includeTimeAnnounced) {
		this.includeTimeAnnounced = includeTimeAnnounced;
	}

	public char getIncludeTimeAllowed() {
		return this.includeTimeAllowed;
	}

	public void setIncludeTimeAllowed(char includeTimeAllowed) {
		this.includeTimeAllowed = includeTimeAllowed;
	}

	public char getUseAccessNumberGroups() {
		return this.useAccessNumberGroups;
	}

	public void setUseAccessNumberGroups(char useAccessNumberGroups) {
		this.useAccessNumberGroups = useAccessNumberGroups;
	}

	public BigDecimal getMaintFeeFrequency() {
		return this.maintFeeFrequency;
	}

	public void setMaintFeeFrequency(BigDecimal maintFeeFrequency) {
		this.maintFeeFrequency = maintFeeFrequency;
	}

	public BigDecimal getSurcharge() {
		return this.surcharge;
	}

	public void setSurcharge(BigDecimal surcharge) {
		this.surcharge = surcharge;
	}

	public BigDecimal getSubrateNotfoundOption() {
		return this.subrateNotfoundOption;
	}

	public void setSubrateNotfoundOption(BigDecimal subrateNotfoundOption) {
		this.subrateNotfoundOption = subrateNotfoundOption;
	}

	public Date getEffectiveDate() {
		return this.effectiveDate;
	}

	public void setEffectiveDate(Date effectiveDate) {
		this.effectiveDate = effectiveDate;
	}

	public Date getEndDate() {
		return this.endDate;
	}

	public void setEndDate(Date endDate) {
		this.endDate = endDate;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public String getRateName() {
		return this.rateName;
	}

	public void setRateName(String rateName) {
		this.rateName = rateName;
	}

	public BigDecimal getFirstMaintFeeFrequency() {
		return this.firstMaintFeeFrequency;
	}

	public void setFirstMaintFeeFrequency(BigDecimal firstMaintFeeFrequency) {
		this.firstMaintFeeFrequency = firstMaintFeeFrequency;
	}

	public BigDecimal getFirstMaintFeeRate() {
		return this.firstMaintFeeRate;
	}

	public void setFirstMaintFeeRate(BigDecimal firstMaintFeeRate) {
		this.firstMaintFeeRate = firstMaintFeeRate;
	}

	public char getTdwDiscountFlag() {
		return this.tdwDiscountFlag;
	}

	public void setTdwDiscountFlag(char tdwDiscountFlag) {
		this.tdwDiscountFlag = tdwDiscountFlag;
	}

	public char getBucketExhaustionCutoffFlag() {
		return this.bucketExhaustionCutoffFlag;
	}

	public void setBucketExhaustionCutoffFlag(char bucketExhaustionCutoffFlag) {
		this.bucketExhaustionCutoffFlag = bucketExhaustionCutoffFlag;
	}

	public char getSendViolationNotifications() {
		return this.sendViolationNotifications;
	}

	public void setSendViolationNotifications(char sendViolationNotifications) {
		this.sendViolationNotifications = sendViolationNotifications;
	}

	public char getSendBucketRefillNotifFlag() {
		return this.sendBucketRefillNotifFlag;
	}

	public void setSendBucketRefillNotifFlag(char sendBucketRefillNotifFlag) {
		this.sendBucketRefillNotifFlag = sendBucketRefillNotifFlag;
	}

	public char getSendBucketExhaustNotifFlag() {
		return this.sendBucketExhaustNotifFlag;
	}

	public void setSendBucketExhaustNotifFlag(char sendBucketExhaustNotifFlag) {
		this.sendBucketExhaustNotifFlag = sendBucketExhaustNotifFlag;
	}

	public BigDecimal getBucketSize() {
		return this.bucketSize;
	}

	public void setBucketSize(BigDecimal bucketSize) {
		this.bucketSize = bucketSize;
	}

	public BigDecimal getNumBucketRefillsPerCycle() {
		return this.numBucketRefillsPerCycle;
	}

	public void setNumBucketRefillsPerCycle(BigDecimal numBucketRefillsPerCycle) {
		this.numBucketRefillsPerCycle = numBucketRefillsPerCycle;
	}

	public BigDecimal getDailyUsageThreshold() {
		return this.dailyUsageThreshold;
	}

	public void setDailyUsageThreshold(BigDecimal dailyUsageThreshold) {
		this.dailyUsageThreshold = dailyUsageThreshold;
	}

	public BigDecimal getBucketRefillWarnThrshld() {
		return this.bucketRefillWarnThrshld;
	}

	public void setBucketRefillWarnThrshld(BigDecimal bucketRefillWarnThrshld) {
		this.bucketRefillWarnThrshld = bucketRefillWarnThrshld;
	}

	public BigDecimal getBucketExhaustWarnThrshld() {
		return this.bucketExhaustWarnThrshld;
	}

	public void setBucketExhaustWarnThrshld(BigDecimal bucketExhaustWarnThrshld) {
		this.bucketExhaustWarnThrshld = bucketExhaustWarnThrshld;
	}

	public BigDecimal getRegionFeeSchedId() {
		return this.regionFeeSchedId;
	}

	public void setRegionFeeSchedId(BigDecimal regionFeeSchedId) {
		this.regionFeeSchedId = regionFeeSchedId;
	}

	public char getBucketPlanType() {
		return this.bucketPlanType;
	}

	public void setBucketPlanType(char bucketPlanType) {
		this.bucketPlanType = bucketPlanType;
	}

	public char getBucketRateCallsFlag() {
		return this.bucketRateCallsFlag;
	}

	public void setBucketRateCallsFlag(char bucketRateCallsFlag) {
		this.bucketRateCallsFlag = bucketRateCallsFlag;
	}

	public BigDecimal getSubscriptionFeeFrequency() {
		return this.subscriptionFeeFrequency;
	}

	public void setSubscriptionFeeFrequency(BigDecimal subscriptionFeeFrequency) {
		this.subscriptionFeeFrequency = subscriptionFeeFrequency;
	}

	public BigDecimal getGracePeriod() {
		return this.gracePeriod;
	}

	public void setGracePeriod(BigDecimal gracePeriod) {
		this.gracePeriod = gracePeriod;
	}

	public BigDecimal getAmountSetting() {
		return this.amountSetting;
	}

	public void setAmountSetting(BigDecimal amountSetting) {
		this.amountSetting = amountSetting;
	}

	public BigDecimal getSurchargeSetting() {
		return this.surchargeSetting;
	}

	public void setSurchargeSetting(BigDecimal surchargeSetting) {
		this.surchargeSetting = surchargeSetting;
	}

	public BigDecimal getMaintFeeStartSeq() {
		return this.maintFeeStartSeq;
	}

	public void setMaintFeeStartSeq(BigDecimal maintFeeStartSeq) {
		this.maintFeeStartSeq = maintFeeStartSeq;
	}

	public BigDecimal getFirstUseThreshold() {
		return this.firstUseThreshold;
	}

	public void setFirstUseThreshold(BigDecimal firstUseThreshold) {
		this.firstUseThreshold = firstUseThreshold;
	}

	public BigDecimal getMaintFeeDayOfWeek() {
		return this.maintFeeDayOfWeek;
	}

	public void setMaintFeeDayOfWeek(BigDecimal maintFeeDayOfWeek) {
		this.maintFeeDayOfWeek = maintFeeDayOfWeek;
	}

	public Set getRatedEvents() {
		return this.ratedEvents;
	}

	public void setRatedEvents(Set ratedEvents) {
		this.ratedEvents = ratedEvents;
	}

}
