package com.beachdog.primusCore.model;

// Generated Mar 1, 2012 2:19:03 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;

/**
 * SvcPrepaidCalling generated by hbm2java
 */
public class SvcPrepaidCalling implements java.io.Serializable {

	private BigDecimal serviceId;
	private BigDecimal longCallInterval;
	private BigDecimal maxRedialsAllowed;
	private char playBalanceFlag;
	private char playTimeFlag;
	private char allowMultipartyCalling;
	private char accessNumRatingFlag;
	private char precallRoundingFlag;
	private char partialBongChargeFlag;
	private char clickToDialFlag;
	private char twoStageDialFlag;
	private char singleStageDialFlag;
	private char msgInitiatedCallbackFlag;
	private char accessNbrInitCallbackFlag;
	private char ivrInitiatedCallbackFlag;
	private char lastCallRedialFlag;
	private char directCallFlag;
	private Character disabledFlag;
	private char useAccessNumberGroups;
	private BigDecimal maxParties;
	private BigDecimal callMarkupPercent;
	private BigDecimal warningThreshold1;
	private BigDecimal warningThreshold2;
	private BigDecimal warningThreshold3;
	private BigDecimal minBillingSeconds;
	private BigDecimal roundingSeconds;
	private BigDecimal roundingThreshold;
	private BigDecimal directCallIdLength;
	private char allowZeroCostFlag;
	private char warningAsToneFlag;
	private Character sequenceRatingFlag;

	public SvcPrepaidCalling() {
	}

	public SvcPrepaidCalling(BigDecimal serviceId, BigDecimal longCallInterval,
			BigDecimal maxRedialsAllowed, char playBalanceFlag,
			char playTimeFlag, char allowMultipartyCalling,
			char accessNumRatingFlag, char precallRoundingFlag,
			char partialBongChargeFlag, char clickToDialFlag,
			char twoStageDialFlag, char singleStageDialFlag,
			char msgInitiatedCallbackFlag, char accessNbrInitCallbackFlag,
			char ivrInitiatedCallbackFlag, char lastCallRedialFlag,
			char directCallFlag, char useAccessNumberGroups,
			char allowZeroCostFlag, char warningAsToneFlag) {
		this.serviceId = serviceId;
		this.longCallInterval = longCallInterval;
		this.maxRedialsAllowed = maxRedialsAllowed;
		this.playBalanceFlag = playBalanceFlag;
		this.playTimeFlag = playTimeFlag;
		this.allowMultipartyCalling = allowMultipartyCalling;
		this.accessNumRatingFlag = accessNumRatingFlag;
		this.precallRoundingFlag = precallRoundingFlag;
		this.partialBongChargeFlag = partialBongChargeFlag;
		this.clickToDialFlag = clickToDialFlag;
		this.twoStageDialFlag = twoStageDialFlag;
		this.singleStageDialFlag = singleStageDialFlag;
		this.msgInitiatedCallbackFlag = msgInitiatedCallbackFlag;
		this.accessNbrInitCallbackFlag = accessNbrInitCallbackFlag;
		this.ivrInitiatedCallbackFlag = ivrInitiatedCallbackFlag;
		this.lastCallRedialFlag = lastCallRedialFlag;
		this.directCallFlag = directCallFlag;
		this.useAccessNumberGroups = useAccessNumberGroups;
		this.allowZeroCostFlag = allowZeroCostFlag;
		this.warningAsToneFlag = warningAsToneFlag;
	}

	public SvcPrepaidCalling(BigDecimal serviceId, BigDecimal longCallInterval,
			BigDecimal maxRedialsAllowed, char playBalanceFlag,
			char playTimeFlag, char allowMultipartyCalling,
			char accessNumRatingFlag, char precallRoundingFlag,
			char partialBongChargeFlag, char clickToDialFlag,
			char twoStageDialFlag, char singleStageDialFlag,
			char msgInitiatedCallbackFlag, char accessNbrInitCallbackFlag,
			char ivrInitiatedCallbackFlag, char lastCallRedialFlag,
			char directCallFlag, Character disabledFlag,
			char useAccessNumberGroups, BigDecimal maxParties,
			BigDecimal callMarkupPercent, BigDecimal warningThreshold1,
			BigDecimal warningThreshold2, BigDecimal warningThreshold3,
			BigDecimal minBillingSeconds, BigDecimal roundingSeconds,
			BigDecimal roundingThreshold, BigDecimal directCallIdLength,
			char allowZeroCostFlag, char warningAsToneFlag,
			Character sequenceRatingFlag) {
		this.serviceId = serviceId;
		this.longCallInterval = longCallInterval;
		this.maxRedialsAllowed = maxRedialsAllowed;
		this.playBalanceFlag = playBalanceFlag;
		this.playTimeFlag = playTimeFlag;
		this.allowMultipartyCalling = allowMultipartyCalling;
		this.accessNumRatingFlag = accessNumRatingFlag;
		this.precallRoundingFlag = precallRoundingFlag;
		this.partialBongChargeFlag = partialBongChargeFlag;
		this.clickToDialFlag = clickToDialFlag;
		this.twoStageDialFlag = twoStageDialFlag;
		this.singleStageDialFlag = singleStageDialFlag;
		this.msgInitiatedCallbackFlag = msgInitiatedCallbackFlag;
		this.accessNbrInitCallbackFlag = accessNbrInitCallbackFlag;
		this.ivrInitiatedCallbackFlag = ivrInitiatedCallbackFlag;
		this.lastCallRedialFlag = lastCallRedialFlag;
		this.directCallFlag = directCallFlag;
		this.disabledFlag = disabledFlag;
		this.useAccessNumberGroups = useAccessNumberGroups;
		this.maxParties = maxParties;
		this.callMarkupPercent = callMarkupPercent;
		this.warningThreshold1 = warningThreshold1;
		this.warningThreshold2 = warningThreshold2;
		this.warningThreshold3 = warningThreshold3;
		this.minBillingSeconds = minBillingSeconds;
		this.roundingSeconds = roundingSeconds;
		this.roundingThreshold = roundingThreshold;
		this.directCallIdLength = directCallIdLength;
		this.allowZeroCostFlag = allowZeroCostFlag;
		this.warningAsToneFlag = warningAsToneFlag;
		this.sequenceRatingFlag = sequenceRatingFlag;
	}

	public BigDecimal getServiceId() {
		return this.serviceId;
	}

	public void setServiceId(BigDecimal serviceId) {
		this.serviceId = serviceId;
	}

	public BigDecimal getLongCallInterval() {
		return this.longCallInterval;
	}

	public void setLongCallInterval(BigDecimal longCallInterval) {
		this.longCallInterval = longCallInterval;
	}

	public BigDecimal getMaxRedialsAllowed() {
		return this.maxRedialsAllowed;
	}

	public void setMaxRedialsAllowed(BigDecimal maxRedialsAllowed) {
		this.maxRedialsAllowed = maxRedialsAllowed;
	}

	public char getPlayBalanceFlag() {
		return this.playBalanceFlag;
	}

	public void setPlayBalanceFlag(char playBalanceFlag) {
		this.playBalanceFlag = playBalanceFlag;
	}

	public char getPlayTimeFlag() {
		return this.playTimeFlag;
	}

	public void setPlayTimeFlag(char playTimeFlag) {
		this.playTimeFlag = playTimeFlag;
	}

	public char getAllowMultipartyCalling() {
		return this.allowMultipartyCalling;
	}

	public void setAllowMultipartyCalling(char allowMultipartyCalling) {
		this.allowMultipartyCalling = allowMultipartyCalling;
	}

	public char getAccessNumRatingFlag() {
		return this.accessNumRatingFlag;
	}

	public void setAccessNumRatingFlag(char accessNumRatingFlag) {
		this.accessNumRatingFlag = accessNumRatingFlag;
	}

	public char getPrecallRoundingFlag() {
		return this.precallRoundingFlag;
	}

	public void setPrecallRoundingFlag(char precallRoundingFlag) {
		this.precallRoundingFlag = precallRoundingFlag;
	}

	public char getPartialBongChargeFlag() {
		return this.partialBongChargeFlag;
	}

	public void setPartialBongChargeFlag(char partialBongChargeFlag) {
		this.partialBongChargeFlag = partialBongChargeFlag;
	}

	public char getClickToDialFlag() {
		return this.clickToDialFlag;
	}

	public void setClickToDialFlag(char clickToDialFlag) {
		this.clickToDialFlag = clickToDialFlag;
	}

	public char getTwoStageDialFlag() {
		return this.twoStageDialFlag;
	}

	public void setTwoStageDialFlag(char twoStageDialFlag) {
		this.twoStageDialFlag = twoStageDialFlag;
	}

	public char getSingleStageDialFlag() {
		return this.singleStageDialFlag;
	}

	public void setSingleStageDialFlag(char singleStageDialFlag) {
		this.singleStageDialFlag = singleStageDialFlag;
	}

	public char getMsgInitiatedCallbackFlag() {
		return this.msgInitiatedCallbackFlag;
	}

	public void setMsgInitiatedCallbackFlag(char msgInitiatedCallbackFlag) {
		this.msgInitiatedCallbackFlag = msgInitiatedCallbackFlag;
	}

	public char getAccessNbrInitCallbackFlag() {
		return this.accessNbrInitCallbackFlag;
	}

	public void setAccessNbrInitCallbackFlag(char accessNbrInitCallbackFlag) {
		this.accessNbrInitCallbackFlag = accessNbrInitCallbackFlag;
	}

	public char getIvrInitiatedCallbackFlag() {
		return this.ivrInitiatedCallbackFlag;
	}

	public void setIvrInitiatedCallbackFlag(char ivrInitiatedCallbackFlag) {
		this.ivrInitiatedCallbackFlag = ivrInitiatedCallbackFlag;
	}

	public char getLastCallRedialFlag() {
		return this.lastCallRedialFlag;
	}

	public void setLastCallRedialFlag(char lastCallRedialFlag) {
		this.lastCallRedialFlag = lastCallRedialFlag;
	}

	public char getDirectCallFlag() {
		return this.directCallFlag;
	}

	public void setDirectCallFlag(char directCallFlag) {
		this.directCallFlag = directCallFlag;
	}

	public Character getDisabledFlag() {
		return this.disabledFlag;
	}

	public void setDisabledFlag(Character disabledFlag) {
		this.disabledFlag = disabledFlag;
	}

	public char getUseAccessNumberGroups() {
		return this.useAccessNumberGroups;
	}

	public void setUseAccessNumberGroups(char useAccessNumberGroups) {
		this.useAccessNumberGroups = useAccessNumberGroups;
	}

	public BigDecimal getMaxParties() {
		return this.maxParties;
	}

	public void setMaxParties(BigDecimal maxParties) {
		this.maxParties = maxParties;
	}

	public BigDecimal getCallMarkupPercent() {
		return this.callMarkupPercent;
	}

	public void setCallMarkupPercent(BigDecimal callMarkupPercent) {
		this.callMarkupPercent = callMarkupPercent;
	}

	public BigDecimal getWarningThreshold1() {
		return this.warningThreshold1;
	}

	public void setWarningThreshold1(BigDecimal warningThreshold1) {
		this.warningThreshold1 = warningThreshold1;
	}

	public BigDecimal getWarningThreshold2() {
		return this.warningThreshold2;
	}

	public void setWarningThreshold2(BigDecimal warningThreshold2) {
		this.warningThreshold2 = warningThreshold2;
	}

	public BigDecimal getWarningThreshold3() {
		return this.warningThreshold3;
	}

	public void setWarningThreshold3(BigDecimal warningThreshold3) {
		this.warningThreshold3 = warningThreshold3;
	}

	public BigDecimal getMinBillingSeconds() {
		return this.minBillingSeconds;
	}

	public void setMinBillingSeconds(BigDecimal minBillingSeconds) {
		this.minBillingSeconds = minBillingSeconds;
	}

	public BigDecimal getRoundingSeconds() {
		return this.roundingSeconds;
	}

	public void setRoundingSeconds(BigDecimal roundingSeconds) {
		this.roundingSeconds = roundingSeconds;
	}

	public BigDecimal getRoundingThreshold() {
		return this.roundingThreshold;
	}

	public void setRoundingThreshold(BigDecimal roundingThreshold) {
		this.roundingThreshold = roundingThreshold;
	}

	public BigDecimal getDirectCallIdLength() {
		return this.directCallIdLength;
	}

	public void setDirectCallIdLength(BigDecimal directCallIdLength) {
		this.directCallIdLength = directCallIdLength;
	}

	public char getAllowZeroCostFlag() {
		return this.allowZeroCostFlag;
	}

	public void setAllowZeroCostFlag(char allowZeroCostFlag) {
		this.allowZeroCostFlag = allowZeroCostFlag;
	}

	public char getWarningAsToneFlag() {
		return this.warningAsToneFlag;
	}

	public void setWarningAsToneFlag(char warningAsToneFlag) {
		this.warningAsToneFlag = warningAsToneFlag;
	}

	public Character getSequenceRatingFlag() {
		return this.sequenceRatingFlag;
	}

	public void setSequenceRatingFlag(Character sequenceRatingFlag) {
		this.sequenceRatingFlag = sequenceRatingFlag;
	}

}
